src/Entity/Application.php
<?php

namespace App\Entity;

use App\Repository\ApplicationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ApplicationRepository::class)]
class Application
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'applications')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $applicant = null;

    #[ORM\ManyToOne(inversedBy: 'applications')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Mobility $mobility = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $applicationDate = null;

    #[ORM\Column(nullable: true)]
    private ?bool $status = null;

    #[ORM\ManyToOne(inversedBy: 'outgoingApplications')]
    private ?Grade $sourceGrade = null;

    #[ORM\Column(nullable: true)]
    private ?bool $verified = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getApplicant(): ?User
    {
        return $this->applicant;
    }

    public function setApplicant(?User $applicant): self
    {
        $this->applicant = $applicant;
        $this->sourceGrade = $applicant->getCurrentYear()?->getGrade()->addOutgoingApplication($this);

        return $this;
    }

    public function getMobility(): ?Mobility
    {
        return $this->mobility;
    }

    public function setMobility(?Mobility $mobility): self
    {
        $this->mobility = $mobility;

        return $this;
    }

    public function getApplicationDate(): ?\DateTimeInterface
    {
        return $this->applicationDate;
    }

    public function setApplicationDate(\DateTimeInterface $applicationDate): self
    {
        $this->applicationDate = $applicationDate;

        return $this;
    }

    public function isStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(?bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getSourceGrade(): ?Grade
    {
        return $this->sourceGrade;
    }

    public function isVerified(): ?bool
    {
        return $this->verified;
    }

    public function setVerified(?bool $verified): self
    {
        $this->verified = $verified;
        $this->applicant->getCurrentYear()?->setAuthentic($verified);
        $this->status = null;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\Common\Collections\Collection;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column(length: 300)]
    private ?string $name = null;

    #[ORM\OneToMany(mappedBy: 'certified', targetEntity: CertificationDetail::class, orphanRemoval: true)]
    private Collection $certificationDetails;

    #[ORM\OneToMany(mappedBy: 'applicant', targetEntity: Application::class, orphanRemoval: true)]
    private Collection $applications;

    #[ORM\OneToMany(mappedBy: 'student', targetEntity: YearDetail::class, orphanRemoval: true)]
    private Collection $yearDetails;

    #[ORM\ManyToOne(inversedBy: 'managers')]
    private ?Institution $institution = null;

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(length: 666, nullable: true)]
    private ?string $photoUrl = null;

    #[ORM\Column(nullable: true)]
    private ?bool $gender = null;

    #[ORM\Column(length: 255)]
    private ?string $nationality = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $birthDate = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $googleId;

    #[ORM\Column(type: 'text', nullable: true)]
    private $avatar ;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $hostedDomain = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }
    public function getGoogleId(): ?string
    {
        return $this->googleId;
    }

    public function setGoogleId(string $googleId): self
    {
        $this->googleId = $googleId;

        return $this;
    }
    public function getHostedDomain(): ?string
    {
        return $this->hostedDomain;
    }

    public function setHostedDomain(string $hostedDomain): self
    {
        $this->hostedDomain = $hostedDomain;

        return $this;
    }
    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @return Collection<int, CertificationDetail>
     */
    public function getCertificationDetails(): Collection
    {
        return $this->certificationDetails;
    }

    public function addCertificationDetail(CertificationDetail $certificationDetail): self
    {
        if (!$this->certificationDetails->contains($certificationDetail)) {
            $this->certificationDetails->add($certificationDetail);
            $certificationDetail->setCertified($this);
        }

        return $this;
    }

    public function removeCertificationDetail(CertificationDetail $certificationDetail): self
    {
        if ($this->certificationDetails->removeElement($certificationDetail)) {
            // set the owning side to null (unless already changed)
            if ($certificationDetail->getCertified() === $this) {
                $certificationDetail->setCertified(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Application>
     */
    public function getApplications(): Collection
    {
        return $this->applications;
    }

    public function addApplication(Application $application): self
    {
        if (!$this->applications->contains($application)) {
            $this->applications->add($application);
            $application->setApplicant($this);
        }

        return $this;
    }

    public function removeApplication(Application $application): self
    {
        if ($this->applications->removeElement($application)) {
            // set the owning side to null (unless already changed)
            if ($application->getApplicant() === $this) {
                $application->setApplicant(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, YearDetail>
     */
    public function getYearDetails(): Collection
    {
        return $this->yearDetails;
    }

    public function addYearDetail(YearDetail $yearDetail): self
    {
        if (!$this->yearDetails->contains($yearDetail)) {
            $this->yearDetails->add($yearDetail);
            $yearDetail->setStudent($this);
        }

        return $this;
    }

    public function removeYearDetail(YearDetail $yearDetail): self
    {
        if ($this->yearDetails->removeElement($yearDetail)) {
            // set the owning side to null (unless already changed)
            if ($yearDetail->getStudent() === $this) {
                $yearDetail->setStudent(null);
            }
        }

        return $this;
    }

    public function getInstitution(): ?Institution
    {
        return $this->institution;
    }

    public function setInstitution(?Institution $institution): self
    {
        $this->institution = $institution;

        return $this;
    }

    public function getCurrentYear(): ?YearDetail
    {
        $currentAcademicYear = (date('m') < 10) ? date('Y') : date('Y') + 1;
        foreach (array_reverse($this->getYearDetails()->toArray()) as $yearDetail) {
            if ($yearDetail->getAcademicYear() == $currentAcademicYear) {
                return $yearDetail;
            }
        }
        return null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getPhotoUrl(): ?string
    {
        return $this->photoUrl;
    }

    public function setPhotoUrl(?string $photoUrl): self
    {
        $this->photoUrl = $photoUrl;

        return $this;
    }

    public function isGender(): ?bool
    {
        return $this->gender;
    }

    public function setGender(?bool $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getNationality(): ?string
    {
        return $this->nationality;
    }

    public function getNationalityFlag(): ?string
    {
        if (strlen($this->nationality) == 2) {
            $regionalOffset = 0x1F1A5;

            return mb_chr($regionalOffset + mb_ord($this->nationality[0], 'UTF-8'), 'UTF-8')
                . mb_chr($regionalOffset + mb_ord($this->nationality[1], 'UTF-8'), 'UTF-8');
        }
        return '!';
    }

    public function setNationality(string $nationality): self
    {
        $this->nationality = $nationality;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthDate(\DateTimeInterface $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }
}

src/Form/ApplicationType.php
<?php

namespace App\Form;

use App\Entity\Application;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ApplicationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Application::class,
        ]);
    }
}

src/Controller/ApplicationController.php
<?php

namespace App\Controller;

use App\Entity\Application;
use App\Repository\ApplicationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/application')]
class ApplicationController extends AbstractController
{
    #[Route('/', name: 'app_application_index', methods: ['GET'])]
    public function index(ApplicationRepository $applicationRepository): Response
    {
        return $this->render('application/index.html.twig', [
            'applications' => $applicationRepository->findAll(),
        ]);
    }

    #[Route('/{id}', name: 'app_application_show', methods: ['GET'])]
    public function show(Application $application): Response
    {
        return $this->render('application/show.html.twig', [
            'application' => $application,
        ]);
    }

    #[Route('/{id}/edit-status/{r}', name: 'app_application_edit_status', methods: ['GET', 'POST'])]
    public function editStatus(Request $request, Application $application, ApplicationRepository $applicationRepository): Response
    {
        $application->setStatus($request->get('r') != 0);
        $applicationRepository->add($application, true);

        return $this->redirectToRoute('app_mobility_show', ['id' => $application->getMobility()->getId()]);
    }

    #[Route('/{id}/edit-verified/{r}', name: 'app_application_edit_verified', methods: ['GET', 'POST'])]
    public function editVerified(Request $request, Application $application, ApplicationRepository $applicationRepository): Response
    {
        $application->setVerified($request->get('r') != 0);
        $applicationRepository->add($application, true);

        return $this->redirectToRoute('app_grade_edit', ['id' => $application->getSourceGrade()->getId()]);
    }

    #[Route('/{id}', name: 'app_application_delete', methods: ['POST'])]
    public function delete(Request $request, Application $application, ApplicationRepository $applicationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $application->getId(), $request->request->get('_token'))) {
            $applicationRepository->remove($application, true);
        }

        return $this->redirectToRoute('app_mobility_show', ['id' => $application->getMobility()->getId()], Response::HTTP_SEE_OTHER);
    }
}

templates/application/_delete_form.html.twig
<form method="post" action="{{ path('app_application_delete', {'id': application.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ application.id) }}">
    <button class="btn delete-btn">Cancel Application</button>
</form>

templates/application/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn save-btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/application/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Application{% endblock %}

{% block body %}
    <h1>Edit Application</h1>

    {{ include('application/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_application_index') }}">back to list</a>

    {{ include('application/_delete_form.html.twig') }}
{% endblock %}

templates/application/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Application index
{% endblock %}

{% block body %}
<h1>
	{% if title is defined %}
	{{ title }}
	{% else %}
	Application index
	{% endif %}
</h1>

<table id="applications" class="table horizontal">
	<thead>
		<tr>
			<th>Applicant</th>
			<th>Current Grade</th>
			<th>ApplicationDate</th>
			{% if includedIn is defined and includedIn == 'grade/edit' %}
			<th>Verified</th>
			{% endif %}
			<th>Accepted</th>
			<th>actions</th>
		</tr>
	</thead>
	<tbody>
		{% if includedIn is not defined or includedIn is defined and includedIn != 'grade/edit' %}
		{% set cachedApplication = null %}
		{% endif %}
		{% for application in applications %}
		<tr class="{{
			(app.user == application.applicant)?
				(application.verified is null and application.status is null)?
				'owned-row' : (application.status == true)? 'approved-row' : (application.verified == true)? 'proved-row': 'rejected-row'
		}}">
			<td>
				<a href=" {{ path('app_user_show', {'id': application.applicant.id}) }}" class="link-btnshow-link-">
					<img src="{{ application.applicant.photoUrl }}">
					{{ application.applicant.name }}
				</a>
			</td>
			<td>
				{% if application.applicant.currentYear is not null %}
				<a href="{{ path('app_year_detail_show', {'id': application.applicant.currentYear.id}) }}"
					class="link-btnshow-link-">
					{{ application.applicant.currentYear.grade.institution.name}}
					({{ application.applicant.currentYear.grade.name}})
				</a>
				{% else %}
				Not Specified
				{% endif %}
			</td>
			<td>{{ application.applicationDate ? application.applicationDate|date('Y-m-d') : '' }}</td>
			{% if includedIn is defined and includedIn == 'grade/edit' %}
			<td>{{ application.verified is null ? 'Not Reviewed': application.verified ? 'Yes' : 'No' }}</td>
			{% endif %}
			<td>
				{% if application.verified %}
				{{ application.status is null ? 'Not viewed': application.status ? 'Yes' : 'No' }}
				{% else %}
				Unavailable
				{% endif %}
			</td>
			<td>
				<a href="{{ path('app_application_show', {'id': application.id}) }}"
					class="link-btnshow-link-btnshow-action-">
					show
				</a>
				{% if includedIn is not defined or includedIn is defined and includedIn != "grade/edit" %}
				{% if app.user.institution == application.mobility.institution %}
				{% if application.status is null or application.status == false %}
				<a href="{{ path('app_application_edit_status', {'id': application.id, 'r': 1}) }}">Accept</a>
				{% endif %}
				{% if application.status is null or application.status == true %}
				<a href="{{ path('app_application_edit_status', {'id': application.id, 'r': 0}) }}">Reject</a>
				{% endif %}
				{% endif %}
				{% else %}
				{% if application.verified is null or application.verified == false %}
				<a href="{{ path('app_application_edit_verified', {'id': application.id, 'r': 1}) }}">Accept</a>
				{% endif %}
				{% if application.verified is null or application.verified == true %}
				<a href="{{ path('app_application_edit_verified', {'id': application.id, 'r': 0}) }}">Reject</a>
				{% endif %}
				{% endif %}
			</td>
		</tr>
		{% if includedIn is not defined or includedIn is defined and includedIn != 'grade/edit' %}
		{% if application in app.user.applications %}
		{% set cachedApplication = application %}
		{% endif %}
		{% endif %}
		{% else %}
		<tr>
			<td colspan="4">no records found</td>
		</tr>
		{% endfor %}
	</tbody>
</table>

{% if (includedIn is not defined or includedIn is defined and includedIn != 'grade/edit') and mobility is defined and
mobility is not null and currdate < mobility.startDate and mobility.size> mobility.applications|filter(a => a.status ==
	true)|length %}
	{% if cachedApplication is null %}
	<a href="{{ path('app_application_new', {'id': mobility.id}) }}">Apply</a>
	{% elseif cachedApplication.status is null %}
	<a href="{{ path('app_application_delete', {'id': cachedApplication.id}) }}">Cancel Application</a>
	{% endif %}
	{% endif %}

	{% endblock %}

templates/application/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Application{% endblock %}

{% block body %}
    <div class="parentContainer">
    <h1>Create new Application</h1>

    {% form_theme form 'bootstrap_5_horizontal_layout.html.twig' %}
    {{ include('application/_form.html.twig') }}

    <a href="{{ path('app_application_index') }}">back to list</a>
    </div>
{% endblock %}

templates/application/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Application
{% endblock %}

{% block body %}
<h1>Application</h1>

<table class="table vertical">
	<tbody>
		{% if app.user in application.mobility.institution.managers %}
		<tr>
			<th>Action</th>
			<td>
				{% if application.status is null %}
				<a href="{{ path('app_application_edit_status', {'id': application.id, 'r': 1}) }}">Accept</a>
				<a href="{{ path('app_application_edit_status', {'id': application.id, 'r': 0}) }}">Reject</a>
				{% else %}
				{% if application.status %}
				<a href="{{ path('app_application_edit_status', {'id': application.id, 'r': 0}) }}">Change and Reject</a>
				{% else %}
				<a href="{{ path('app_application_edit_status', {'id': application.id, 'r': 1}) }}">Change and Accept</a>
				{% endif %}
				{% endif %}
			</td>
		</tr>
		{% endif %}
		<tr>
			<th>Status</th>
			<td>{{ application.status ? 'Yes' : 'No' }}</td>
		</tr>
		<tr>
			<th>Applicant</th>
			<td>
				<a href="{{ path('app_user_show', {'id': application.applicant.id}) }}">
					<img src="{{ application.applicant.photoUrl }}">
					{{ application.applicant.name }}
				</a>
			</td>
		</tr>
		{% if application.applicant.currentYear is not null %}
		<tr>
			<th>Grade</th>
			<td>
				<a href="{{ path('app_grade_show', {'id': application.applicant.currentYear.grade.id}) }}">
					{{ application.applicant.currentYear.grade.institution.name}}
					({{ application.applicant.currentYear.grade.name}})
				</a>
			</td>
		</tr>
		{% endif %}
		<tr>
			<th>Mobility</th>
			<td>
				<a href="{{ path('app_mobility_show', {'id': application.mobility.id}) }}">
					{{ application.mobility.name }}
					({{ application.mobility.institution.name }})
				</a>
			</td>
		</tr>
		<tr>
			<th>ApplicationDate</th>
			<td>{{ application.applicationDate ? application.applicationDate|date('Y-m-d') : '' }}</td>
		</tr>
	</tbody>
</table>

<a href="{{ path('app_mobility_show', {'id': application.mobility.id}) }}">back to mobility</a>

{% if app.user.id == application.applicant.id and application.status is null %}
{{ include('application/_delete_form.html.twig') }}
{% endif %}

{% endblock %}