src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\Common\Collections\Collection;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column(length: 300)]
    private ?string $name = null;

    #[ORM\OneToMany(mappedBy: 'certified', targetEntity: CertificationDetail::class, orphanRemoval: true)]
    private Collection $certificationDetails;

    #[ORM\OneToMany(mappedBy: 'applicant', targetEntity: Application::class, orphanRemoval: true)]
    private Collection $applications;

    #[ORM\OneToMany(mappedBy: 'student', targetEntity: YearDetail::class, orphanRemoval: true)]
    private Collection $yearDetails;

    #[ORM\ManyToOne(inversedBy: 'managers')]
    private ?Institution $institution = null;

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(length: 666, nullable: true)]
    private ?string $photoUrl = null;

    #[ORM\Column(nullable: true)]
    private ?bool $gender = null;

    #[ORM\Column(length: 255)]
    private ?string $nationality = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $birthDate = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $googleId;

    #[ORM\Column(type: 'text', nullable: true)]
    private $avatar ;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $hostedDomain = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }
    public function getGoogleId(): ?string
    {
        return $this->googleId;
    }

    public function setGoogleId(string $googleId): self
    {
        $this->googleId = $googleId;

        return $this;
    }
    public function getHostedDomain(): ?string
    {
        return $this->hostedDomain;
    }

    public function setHostedDomain(string $hostedDomain): self
    {
        $this->hostedDomain = $hostedDomain;

        return $this;
    }
    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @return Collection<int, CertificationDetail>
     */
    public function getCertificationDetails(): Collection
    {
        return $this->certificationDetails;
    }

    public function addCertificationDetail(CertificationDetail $certificationDetail): self
    {
        if (!$this->certificationDetails->contains($certificationDetail)) {
            $this->certificationDetails->add($certificationDetail);
            $certificationDetail->setCertified($this);
        }

        return $this;
    }

    public function removeCertificationDetail(CertificationDetail $certificationDetail): self
    {
        if ($this->certificationDetails->removeElement($certificationDetail)) {
            // set the owning side to null (unless already changed)
            if ($certificationDetail->getCertified() === $this) {
                $certificationDetail->setCertified(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Application>
     */
    public function getApplications(): Collection
    {
        return $this->applications;
    }

    public function addApplication(Application $application): self
    {
        if (!$this->applications->contains($application)) {
            $this->applications->add($application);
            $application->setApplicant($this);
        }

        return $this;
    }

    public function removeApplication(Application $application): self
    {
        if ($this->applications->removeElement($application)) {
            // set the owning side to null (unless already changed)
            if ($application->getApplicant() === $this) {
                $application->setApplicant(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, YearDetail>
     */
    public function getYearDetails(): Collection
    {
        return $this->yearDetails;
    }

    public function addYearDetail(YearDetail $yearDetail): self
    {
        if (!$this->yearDetails->contains($yearDetail)) {
            $this->yearDetails->add($yearDetail);
            $yearDetail->setStudent($this);
        }

        return $this;
    }

    public function removeYearDetail(YearDetail $yearDetail): self
    {
        if ($this->yearDetails->removeElement($yearDetail)) {
            // set the owning side to null (unless already changed)
            if ($yearDetail->getStudent() === $this) {
                $yearDetail->setStudent(null);
            }
        }

        return $this;
    }

    public function getInstitution(): ?Institution
    {
        return $this->institution;
    }

    public function setInstitution(?Institution $institution): self
    {
        $this->institution = $institution;

        return $this;
    }

    public function getCurrentYear(): ?YearDetail
    {
        $currentAcademicYear = (date('m') < 10) ? date('Y') : date('Y') + 1;
        foreach (array_reverse($this->getYearDetails()->toArray()) as $yearDetail) {
            if ($yearDetail->getAcademicYear() == $currentAcademicYear) {
                return $yearDetail;
            }
        }
        return null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getPhotoUrl(): ?string
    {
        return $this->photoUrl;
    }

    public function setPhotoUrl(?string $photoUrl): self
    {
        $this->photoUrl = $photoUrl;

        return $this;
    }

    public function isGender(): ?bool
    {
        return $this->gender;
    }

    public function setGender(?bool $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getNationality(): ?string
    {
        return $this->nationality;
    }

    public function getNationalityFlag(): ?string
    {
        if (strlen($this->nationality) == 2) {
            $regionalOffset = 0x1F1A5;

            return mb_chr($regionalOffset + mb_ord($this->nationality[0], 'UTF-8'), 'UTF-8')
                . mb_chr($regionalOffset + mb_ord($this->nationality[1], 'UTF-8'), 'UTF-8');
        }
        return '!';
    }

    public function setNationality(string $nationality): self
    {
        $this->nationality = $nationality;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthDate(\DateTimeInterface $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }
}

src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UsersRepository::class)]
#[UniqueEntity(fields: ['username'], message: 'There is already an account with this username')]
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $username = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('photoUrl', UrlType::class)
            ->add('name')
            ->add('birthDate', BirthdayType::class, [
                'years' => range(date('Y') - 50, date('Y') - 17),
                'placeholder' => [
                    'year' => 'Year', 'month' => 'Month', 'day' => 'Day',
                ],
            ])
            ->add('gender', ChoiceType::class, [
                'expanded' => true,
                'choices' => [
                    'Male' => true,
                    'Female' => false,
                    'None' => null,
                ],
            ])
            ->add('nationality', CountryType::class, [
                'placeholder' => "Select your Nationality"
            ])
            ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;


#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/', name: 'app_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UserRepository $userRepository, UserPasswordHasherInterface $userPasswordHasher): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );
            $userRepository->add($user, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, UserRepository $userRepository): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->add($user, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $userRepository->remove($user, true);
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
<h1>Edit User</h1>

{{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

<a href="{{ path('app_user_index') }}">back to list</a>

{{ include('user/_delete_form.html.twig') }}

{% if user.certificationDetails is not null and user.certificationDetails|length > 0 %}
{% include "certification_detail/index.html.twig" with {'includedIn': 'user/show', 'certification_details':
user.certificationDetails} %}
{% endif %}
{% if user.yearDetails is not null and user.yearDetails|length > 0 %}
{% include "year_detail/index.html.twig" with {'includedIn': 'user/show', 'year_details': user.yearDetails} %}
{% endif %}

{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
<h1>
    {% if title is defined %}
    {{ title }}
    {% else %}
    User index
    {% endif %}
</h1>

<table class="table horizontal">
    <thead>
        <tr>
            <th>Name</th>
            <th>Gender</th>
            <th>Nationality</th>
            {% if includedIn is not defined or includedIn != 'institution/edit' %}
            <th>Institution</th>
            {% endif %}
            <th>actions</th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}

        <tr {% if user==app.user %} class="owned-row" {% endif %}>
            <td>
                <a href="{{ path('app_user_show', {'id': user.id}) }}">
                    <img src="{{ user.photoUrl }}">
                    {{ user.name }}
                </a>
            </td>
            <td>
                {% if user.gender is not null %}
                {% if user.gender %}
                M
                {% else %}
                F
                {% endif %}
                {% else %}
                !
                {% endif %}
            </td>
            <td>{{ user.nationalityFlag }}</td>
            {% if includedIn is not defined or includedIn != 'institution/edit' %}
            <td>
                {% if user.institution is not null %}
                <a href="{{ path('app_institution_show', {'id': user.institution.id}) }}">
                    <img src="{{ user.institution.photoUrl }}">
                    {{ user.institution.name }}
                </a>
                {% else %}
                Not a manager
                {% endif %}
            </td>
            {% endif %}
            <td>
                {% if institution is defined and app.user.institution is not null and institution.id ==
                app.user.institution.id %}
                {% if user.institution is null %}
                <a href="{{ path('app_institution_edit_managers_add', {'id': institution.id, 'mid': user.id}) }}">
                    Add Manager
                </a>
                {% else %}
                <a href="{{ path('app_institution_edit_managers_remove', {'id': institution.id, 'mid': user.id}) }}">
                    {% if institution.managers|length > 1 %}
                    {% if app.user == user %}
                    Retire
                    {% else %}
                    Remove Manager
                    {% endif %}
                    {% endif %}
                </a>
                {% endif %}
                {% endif %}
                <p>
                    <a href="mailto:{{ user.email }}" target="_blank" rel="noopener noreferrer">
                        email
                    </a>
                </p>
                <p>
                    <a href="{{ path('app_user_show', {'id': user.id}) }}">
                        show
                    </a>
                </p>
            </td>
        </tr>
        {% else %}
        <tr>
            <td colspan="5">no records found</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('app_user_index') }}">back to list</a>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
<h1>User</h1>

<table class="table vertical">
    <tbody>
        <tr>
            <th>Profile Photo</th>
            <td>
                <img src="{{ user.photoUrl }}">
            </td>
        </tr>
        <tr>
            <th>Name</th>
            <td>{{ user.name }}</td>
        </tr>
        <tr>
            <th>Nationality</th>
            <td>
                {% if user.nationality|length != 2 %}
                Not Provided
                {% else %}
                {{ user.nationalityFlag }} {{ user.nationality|country_name }}
                {% endif %}
            </td>
        </tr>
        <tr>
            <th>Birth Date</th>
            <td>{{ user.birthDate|date("d M Y") }}</td>
        </tr>
        <tr>
            <th>Gender</th>
            <td>
                {% if user.gender is null %}
                Not provided
                {% elseif user.gender %}
                Male
                {% else %}
                Female
                {% endif %}
            </td>
        </tr>
        <tr>
            <th>Email</th>
            <td>
                <a href="mailto:{{ user.email }}" target="_blank" rel="noopener noreferrer">
                    {{ user.email }}
                </a>
            </td>
        </tr>
        {% if user.institution is not null %}
        <th>Managed Institution</th>
        <td>
            <a href="{{ path('app_institution_show', {'id': app.user.institution.id}) }}">{{ app.user.institution.name
                }}</a>
        </td>
        {% endif %}
    </tbody>
</table>

<a href="{{ path('app_user_index') }}">back to list</a>

<a href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>

{{ include('user/_delete_form.html.twig') }}

{% if app.user != user %}
{% if user.certificationDetails is not null and user.certificationDetails|length > 0 %}
{% include "certification_detail/index.html.twig" with {'includedIn': 'user/show', 'certification_details':
user.certificationDetails} %}
{% endif %}
{% if user.yearDetails is not null and user.yearDetails|length > 0 %}
{% include "year_detail/index.html.twig" with {'includedIn': 'user/show', 'year_details': user.yearDetails} %}
{% endif %}
{% else %}
{% include "application/index.html.twig" with {'includedIn': 'user/show', 'applications': user.applications} %}
{% endif %}
{% endblock %}