src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\Common\Collections\Collection;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column(length: 300)]
    private ?string $name = null;

    #[ORM\OneToMany(mappedBy: 'certified', targetEntity: CertificationDetail::class, orphanRemoval: true)]
    private Collection $certificationDetails;

    #[ORM\OneToMany(mappedBy: 'applicant', targetEntity: Application::class, orphanRemoval: true)]
    private Collection $applications;

    #[ORM\OneToMany(mappedBy: 'student', targetEntity: YearDetail::class, orphanRemoval: true)]
    private Collection $yearDetails;

    #[ORM\ManyToOne(inversedBy: 'managers')]
    private ?Institution $institution = null;

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(length: 666, nullable: true)]
    private ?string $photoUrl = null;

    #[ORM\Column(nullable: true)]
    private ?bool $gender = null;

    #[ORM\Column(length: 255)]
    private ?string $nationality = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $birthDate = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $googleId;

    #[ORM\Column(type: 'text', nullable: true)]
    private $avatar ;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $hostedDomain = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }
    public function getGoogleId(): ?string
    {
        return $this->googleId;
    }

    public function setGoogleId(string $googleId): self
    {
        $this->googleId = $googleId;

        return $this;
    }
    public function getHostedDomain(): ?string
    {
        return $this->hostedDomain;
    }

    public function setHostedDomain(string $hostedDomain): self
    {
        $this->hostedDomain = $hostedDomain;

        return $this;
    }
    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @return Collection<int, CertificationDetail>
     */
    public function getCertificationDetails(): Collection
    {
        return $this->certificationDetails;
    }

    public function addCertificationDetail(CertificationDetail $certificationDetail): self
    {
        if (!$this->certificationDetails->contains($certificationDetail)) {
            $this->certificationDetails->add($certificationDetail);
            $certificationDetail->setCertified($this);
        }

        return $this;
    }

    public function removeCertificationDetail(CertificationDetail $certificationDetail): self
    {
        if ($this->certificationDetails->removeElement($certificationDetail)) {
            // set the owning side to null (unless already changed)
            if ($certificationDetail->getCertified() === $this) {
                $certificationDetail->setCertified(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Application>
     */
    public function getApplications(): Collection
    {
        return $this->applications;
    }

    public function addApplication(Application $application): self
    {
        if (!$this->applications->contains($application)) {
            $this->applications->add($application);
            $application->setApplicant($this);
        }

        return $this;
    }

    public function removeApplication(Application $application): self
    {
        if ($this->applications->removeElement($application)) {
            // set the owning side to null (unless already changed)
            if ($application->getApplicant() === $this) {
                $application->setApplicant(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, YearDetail>
     */
    public function getYearDetails(): Collection
    {
        return $this->yearDetails;
    }

    public function addYearDetail(YearDetail $yearDetail): self
    {
        if (!$this->yearDetails->contains($yearDetail)) {
            $this->yearDetails->add($yearDetail);
            $yearDetail->setStudent($this);
        }

        return $this;
    }

    public function removeYearDetail(YearDetail $yearDetail): self
    {
        if ($this->yearDetails->removeElement($yearDetail)) {
            // set the owning side to null (unless already changed)
            if ($yearDetail->getStudent() === $this) {
                $yearDetail->setStudent(null);
            }
        }

        return $this;
    }

    public function getInstitution(): ?Institution
    {
        return $this->institution;
    }

    public function setInstitution(?Institution $institution): self
    {
        $this->institution = $institution;

        return $this;
    }

    public function getCurrentYear(): ?YearDetail
    {
        $currentAcademicYear = (date('m') < 10) ? date('Y') : date('Y') + 1;
        foreach (array_reverse($this->getYearDetails()->toArray()) as $yearDetail) {
            if ($yearDetail->getAcademicYear() == $currentAcademicYear) {
                return $yearDetail;
            }
        }
        return null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getPhotoUrl(): ?string
    {
        return $this->photoUrl;
    }

    public function setPhotoUrl(?string $photoUrl): self
    {
        $this->photoUrl = $photoUrl;

        return $this;
    }

    public function isGender(): ?bool
    {
        return $this->gender;
    }

    public function setGender(?bool $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getNationality(): ?string
    {
        return $this->nationality;
    }

    public function getNationalityFlag(): ?string
    {
        if (strlen($this->nationality) == 2) {
            $regionalOffset = 0x1F1A5;

            return mb_chr($regionalOffset + mb_ord($this->nationality[0], 'UTF-8'), 'UTF-8')
                . mb_chr($regionalOffset + mb_ord($this->nationality[1], 'UTF-8'), 'UTF-8');
        }
        return '!';
    }

    public function setNationality(string $nationality): self
    {
        $this->nationality = $nationality;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthDate(\DateTimeInterface $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }
}

src/Form/MobilityType.php
<?php

namespace App\Form;

use App\Entity\Mobility;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MobilityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('description', TextareaType::class)
            ->add('startDate')
            ->add('endDate')
            ->add('size')
            ->add('grades')
            ->add('certs');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Mobility::class,
        ]);
    }
}

src/Controller/MobilityController.php
<?php

namespace App\Controller;

use App\Entity\Mobility;
use App\Entity\Application;
use App\Form\MobilityType;
use App\Form\ApplicationType;
use App\Repository\MobilityRepository;
use App\Repository\ApplicationRepository;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/mobility')]
class MobilityController extends AbstractController
{
    #[Route('/', name: 'app_mobility_index', methods: ['GET'])]
    public function index(MobilityRepository $mobilityRepository): Response
    {
        $suggestedMobilityCriteria = new Criteria();
        $suggestedMobilityExpressionBuilder = Criteria::expr();

        $suggestedMobilityCriteria->where(
            $suggestedMobilityExpressionBuilder->gte('startDate', new \DateTime('now')),
        )->orderBy([
            'startDate' => 'ASC',
        ]);


        return $this->render('mobility/index.html.twig', [
            'mobilities' => $mobilityRepository->matching($suggestedMobilityCriteria),
        ]);
    }

    #[Route('/new', name: 'app_mobility_new', methods: ['GET', 'POST'])]
    public function new(Request $request, MobilityRepository $mobilityRepository): Response
    {
        $mobility = new Mobility();
        $form = $this->createForm(MobilityType::class, $mobility);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $mobility->setInstitution($this->getUser()->getInstitution());
            $mobilityRepository->add($mobility, true);

            return $this->redirectToRoute('app_mobility_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('mobility/new.html.twig', [
            'mobility' => $mobility,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_mobility_show', methods: ['GET'])]
    public function show(Mobility $mobility): Response
    {
        return $this->render('mobility/show.html.twig', [
            'mobility' => $mobility,
            'currdate' => new \DateTime('now'),
        ]);
    }

    #[Route('/{id}/application/new', name: 'app_application_new', methods: ['GET', 'POST'])]
    public function apply(Mobility $mobility, Request $request, ApplicationRepository $applicationRepository): Response
    {
        $application = new Application();
        $form = $this->createForm(ApplicationType::class, $application);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $application->setApplicant($this->getUser());
            $application->setApplicationDate(new \DateTime('now'));
            $mobility->addApplication($application);

            $applicationRepository->add($application, true);

            return $this->redirectToRoute('app_mobility_show', ['id' => $mobility->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('application/new.html.twig', [
            'application' => $application,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_mobility_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Mobility $mobility, MobilityRepository $mobilityRepository): Response
    {
        $form = $this->createForm(MobilityType::class, $mobility);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $mobilityRepository->add($mobility, true);

            return $this->redirectToRoute('app_mobility_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('mobility/edit.html.twig', [
            'mobility' => $mobility,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_mobility_delete', methods: ['POST'])]
    public function delete(Request $request, Mobility $mobility, MobilityRepository $mobilityRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $mobility->getId(), $request->request->get('_token'))) {
            $mobilityRepository->remove($mobility, true);
        }

        return $this->redirectToRoute('app_mobility_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/mobility/_delete_form.html.twig
<form method="post" action="{{ path('app_mobility_delete', {'id': mobility.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ mobility.id) }}">
    <button class="">Delete</button>
</form>

templates/mobility/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/mobility/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Mobility{% endblock %}

{% block body %}
    <h1>Edit Mobility</h1>

    {{ include('mobility/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_mobility_index') }}">back to list</a>

    {{ include('mobility/_delete_form.html.twig') }}
{% endblock %}

templates/mobility/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mobility index{% endblock %}

{% block body %}
<h1>Mobility index</h1>

<table class="table horizontal">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            {% if includedIn is not defined or includedIn != "institution/show" %}
            <th>Host</th>
            {% endif %}
            <th>StartDate</th>
            <th>EndDate</th>
            <th>Applications</th>
            <th>actions</th>
        </tr>
    </thead>
    <tbody>
        {% for mobility in mobilities %}
        <tr {% if (includedIn is not defined or includedIn != 'institution/show') and mobility.institution==app.user.institution %} class="owned-row" {% endif %}>
            <td>{{ mobility.name }}</td>
            <td>{{ mobility.description }}</td>
            {% if includedIn is not defined or includedIn != "institution/show" %}
            <td>
                <a href="{{ path('app_institution_show', {'id': mobility.institution.id}) }}">
                    <img src="{{ mobility.institution.photoUrl }}">
                    {{ mobility.institution.name }}
                </a>
            </td>
            {% endif %}
            <td>{{ mobility.startDate ? mobility.startDate|date('Y-m-d') : '' }}</td>
            <td>{{ mobility.endDate ? mobility.endDate|date('Y-m-d') : '' }}</td>
            <td>
                {{ mobility.applications | filter(application => application.status == true) | length }}
                {% if mobility.size is not null %}
                / {{ mobility.size }}
                {% else %}
                joined
                {% endif %}
                <a href="{{ path('app_mobility_show', {'id': mobility.id, '_fragment': " applications"}) }}">
                    ({{ mobility.applications | filter(application => application.verified and application.status is
                    null) | length }} pending)
                </a>
            </td>
            <td>
                <a href="{{ path('app_mobility_show', {'id': mobility.id}) }}">show</a>
                {% if app.user.institution == mobility.institution %}
                <a href="{{ path('app_mobility_edit', {'id': mobility.id}) }}">edit</a>
                {% endif %}
            </td>
        </tr>
        {% else %}
        <tr>
            <td colspan="7">no records found</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/mobility/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Mobility{% endblock %}

{% block body %}
    <div class="parentContainer">
    <h1>Create new Mobility</h1>

    {% form_theme form 'bootstrap_5_horizontal_layout.html.twig' %}
    {{ include('mobility/_form.html.twig') }}

    <a href="{{ path('app_mobility_index') }}">back to list</a>
    </div>
{% endblock %}

templates/mobility/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mobility{% endblock %}

{% block body %}
<h1>Mobility</h1>

<table class="table vertical">
    <tbody>
        <tr>
            <th>Name</th>
            <td>{{ mobility.name }}</td>
        </tr>
        <tr>
            <th>Institution</th>
            <td>
                <a href="{{ path('app_institution_show', {'id': mobility.institution.id}) }}">
                    <img src="{{ mobility.institution.photoUrl }}">
                    {{ mobility.institution.name }}
                </a>
            </td>
        </tr>
        <tr>
            <th>Grades</th>
            <td>
                {% for grade in mobility.grades %}
                <a href="{{ path('app_grade_show', {'id': grade.id}) }}">
                    {{ grade.name }}
                </a>
                {% else %}
                No Grades required
                {% endfor %}
            </td>
        </tr>
        <tr>
            <th>Certifications</th>
            <td>
                {% for cert in mobility.certs %}
                <a href="{{ path('app_certification_show', {'id': cert.id}) }}">
                    {{ cert.name }}
                </a>
                {% else %}
                No Certifications required
                {% endfor %}
            </td>
        </tr>
        <tr>
            <th>Description</th>
            <td>{{ mobility.description }}</td>
        </tr>
        <tr>
            <th>StartDate</th>
            <td>{{ mobility.startDate ? mobility.startDate|date('Y-m-d') : '' }}</td>
        </tr>
        <tr>
            <th>EndDate</th>
            <td>{{ mobility.endDate ? mobility.endDate|date('Y-m-d') : '' }}</td>
        </tr>
        <tr>
            <th>Accepted Applications</th>
            <td>
                {{ mobility.applications | filter(application => application.status == true) | length }}
                {% if mobility.size is not null %}
                / {{ mobility.size }}
                {% else %}
                joined
                {% endif %}
            </td>
        </tr>
    </tbody>
</table>

<a href="{{ path('app_mobility_index') }}">back to list</a>

{% if app.user.institution == mobility.institution %}
<a href="{{ path('app_mobility_edit', {'id': mobility.id}) }}">edit</a>
{{ include('mobility/_delete_form.html.twig') }}
{% endif %}

{% include "application/index.html.twig" with {'applications': mobility.applications, 'mobility': mobility, 'currdate':
currdate} %}

{% endblock %}